version: "3.9"

services:
  web:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: postgres:15
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase

volumes:
  postgres-data-dev:
