# Generated by Django 3.0.6 on 2023-08-22 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=700, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=255, unique=True)),
                ('class_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DasboardApp.Class1')),
                ('subcat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='DasboardApp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=700)),
                ('quantity', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('SSN', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Name', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('DNUSAN', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Shortdesc', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Class', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Category', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Subcategory', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Manufacturer', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Model', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Status', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Substatus', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Reservedby', models.CharField(blank=True, max_length=700, null=True)),
                ('Configname', models.CharField(blank=True, max_length=700, null=True)),
                ('Program', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Project', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('PONo', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('POlineNo', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Assignto', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Ownedby', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Managedby', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('HomeLoc', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Location', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('LocDetails', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Created', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Createdby', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Updated', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Updatedby', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Costcent', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Comments', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('FinaType', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('HardSuppG', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('HardSuppSer', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('LotNo', models.CharField(blank=True, default=False, max_length=700, null=True)),
                ('Etag', models.CharField(blank=True, default=False, max_length=700, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=255, unique=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DasboardApp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, unique=True)),
                ('class_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DasboardApp.Class1')),
                ('manufacturer_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DasboardApp.Manufacturer')),
                ('subcat_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DasboardApp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=700)),
                ('Category', models.CharField(default=False, max_length=700)),
                ('Manufacturer', models.CharField(default=False, max_length=700)),
                ('Model', models.CharField(default=False, max_length=700)),
                ('quantity', models.CharField(default=False, max_length=700)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='configname', to='DasboardApp.ConfigName')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categories', to='DasboardApp.Class1'),
        ),
    ]
