# Generated by Django 3.0.6 on 2023-06-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DasboardApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Assignto',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Category',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Class',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Comments',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Costcent',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Created',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Createdby',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='DNUSAN',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Etag',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='FinaType',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='HardSuppG',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='HardSuppSer',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='HomeLoc',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LocDetails',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Location',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='LotNo',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Managedby',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Manufacturer',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Model',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Name',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Ownedby',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='PONo',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='POlineNo',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Program',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Project',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='SSN',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Shortdesc',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Status',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Subcategory',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Substatus',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Updated',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Updatedby',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
    ]
