# Generated by Django 3.0.6 on 2023-05-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DasboardApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='Name',
        ),
    ]
