# Generated by Django 3.0.6 on 2023-05-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DasboardApp', '0002_remove_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Name',
            field=models.CharField(default=False, max_length=700),
        ),
    ]
