# Generated by Django 3.0.6 on 2023-06-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DasboardApp', '0003_configname_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configname',
            name='user',
        ),
        migrations.AddField(
            model_name='stock',
            name='Configname',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Reservedby',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
    ]
