# Generated by Django 3.0.6 on 2023-06-30 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DasboardApp', '0005_auto_20230605_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Assigned_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='stock',
            name='Count',
            field=models.CharField(blank=True, default=1, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Reserved_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='stock',
            name='Type',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='item_img',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='vendor_id',
            field=models.CharField(blank=True, default=False, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='warranty_date',
            field=models.CharField(blank=True, default='20/12/24', max_length=700, null=True),
        ),
    ]
