# Generated by Django 3.0.7 on 2023-05-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='SSN',
            field=models.CharField(default=False, max_length=80),
        ),
    ]
