# Generated by Django 3.0.7 on 2023-05-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20230520_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Name',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='SSN',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
