# Generated by Django 3.0.7 on 2023-05-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20230521_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Class',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
