# Generated by Django 3.0.7 on 2023-05-24 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20230524_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='subcat_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.Category'),
        ),
    ]
