# Generated by Django 3.0.7 on 2023-05-24 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_manufacturer_subcat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='subcat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category'),
        ),
    ]
