# Generated by Django 3.0.7 on 2023-05-24 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20230524_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categories', to='inventory.Class'),
        ),
    ]
