# Generated by Django 3.0.7 on 2023-05-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20230524_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Class1',
        ),
    ]
