# Generated by Django 3.0.7 on 2023-05-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20230524_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='manufacturer_name',
        ),
        migrations.AddField(
            model_name='model',
            name='manufacturer_name',
            field=models.ManyToManyField(to='inventory.Manufacturer'),
        ),
    ]
