# Generated by Django 3.0.7 on 2023-05-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20230524_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='class_name',
            field=models.ManyToManyField(to='inventory.Class1'),
        ),
    ]
