# Generated by Django 3.0.7 on 2023-05-24 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_model_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='category_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.Category'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='class_name',
        ),
        migrations.AddField(
            model_name='category',
            name='class_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Categories', to='inventory.Class1'),
        ),
        migrations.RemoveField(
            model_name='model',
            name='class_name',
        ),
        migrations.AddField(
            model_name='model',
            name='class_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.Class1'),
        ),
        migrations.RemoveField(
            model_name='model',
            name='manufacturer_name',
        ),
        migrations.AddField(
            model_name='model',
            name='manufacturer_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.Manufacturer'),
        ),
    ]
