# Generated by Django 3.0.7 on 2023-05-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20230524_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='subcat_name',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category_name',
        ),
    ]
