# Generated by Django 3.0.7 on 2023-05-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20230524_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='model',
            name='class_name',
        ),
    ]
