# Generated by Django 3.0.7 on 2023-05-24 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20230524_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categories', to='inventory.Class1'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='subcat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='inventory.Category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category'),
        ),
    ]
