# Generated by Django 3.0.7 on 2023-05-24 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_auto_20230524_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='class_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.Class1'),
        ),
        migrations.AddField(
            model_name='model',
            name='subcat_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.Category'),
        ),
        migrations.AlterField(
            model_name='model',
            name='manufacturer_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.Manufacturer'),
        ),
    ]
