# Generated by Django 3.0.7 on 2023-05-25 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_auto_20230524_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='class_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.Class1'),
        ),
    ]
