# Generated by Django 3.0.7 on 2023-05-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_config_configname'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='Category',
            field=models.CharField(default=False, max_length=700),
        ),
        migrations.AddField(
            model_name='config',
            name='Manufacturer',
            field=models.CharField(default=False, max_length=700),
        ),
        migrations.AddField(
            model_name='config',
            name='Model',
            field=models.CharField(default=False, max_length=700),
        ),
        migrations.AddField(
            model_name='config',
            name='quantity',
            field=models.CharField(default=False, max_length=700),
        ),
    ]
